[package]
name = "day_three"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"

[profile.release-harder]
opt-level = 3
inherits="release"
codegen-units = 1
lto = "fat"